

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
      
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

