version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './staticfiles:/app/static'
      - './media:/app/media'
    depends_on:
      - backend
    networks:
      - giftly_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn giffly_backend.wsgi:application --bind 0.0.0.0:8000 --config gunicorn_config.py"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=giffly_backend.settings
      - DATABASE_URL=postgres://postgres:1985@db:5432/giftly_db
      - GIGACHAT_CREDENTIALS=YTg5NjI5YmQtY2ZjMy00ODg1LTk3NzgtOGEyMjk0ZjQ2MGFiOjY2NmYyZjQ4LTNiZmItNDAzYy1iMTNlLThlNTRkODRjOWZiOQ==
    depends_on:
      - db
    networks:
      - giftly_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1985
      POSTGRES_DB: giftly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - giftly_network

networks:
  giftly_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:


