# Generated by Django 5.0.2 on 2025-05-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(db_column='seller_id_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.user'),
        ),
    ]
