# Generated by Django 5.0.2 on 2025-05-20 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.user'),
            preserve_default=False,
        ),
    ]
