# Generated by Django 5.0.1 on 2025-05-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email_alter_user_first_name_and_more'),
        ('api', '0002_fix_admin_log'),
    ]

    operations = [
    ]
