# Generated by Django 5.0.2 on 2025-05-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_url',
        ),
    ]
