name: Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: giftly_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1985
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          cd giffly_backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          cd giffly_backend
          python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Проверяем наличие директории
            if [ ! -d "/root/backend_giftly" ]; then
              mkdir -p /root/backend_giftly
            fi
            
            # Переходим в директорию
            cd /root/backend_giftly
            
            # Клонируем репозиторий, если его нет
            if [ ! -d ".git" ]; then
              git clone https://github.com/danielsteblev/backend_giftly.git .
            fi
            
            # Обновляем код
            git pull origin main
            
            # Устанавливаем зависимости
            python3 -m pip install --upgrade pip
            python3 -m pip install -r giffly_backend/requirements.txt
            
            # Применяем миграции
            cd giffly_backend
            python3 manage.py migrate
            python3 manage.py collectstatic --noinput
            
            # Перезапускаем контейнеры
            docker compose down
            docker compose up -d --build 